- job:
    name: telemetry-tempest-base
    parent: devstack-tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
    timeout: 7800
    required-projects: &base_required_projects
      - openstack/devstack-gate
      - openstack/panko
      - openstack/aodh
      - openstack/ceilometer
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      - openstack/dib-utils
      - openstack/diskimage-builder
      - openstack/tempest
    vars: &base_vars
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        ceilometer: https://opendev.org/openstack/ceilometer
        aodh: https://opendev.org/openstack/aodh
        panko: https://opendev.org/openstack/panko
      devstack_services:
        tempest: true
        tls-proxy: false
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/telemetry-tempest-plugin /opt/stack/heat-tempest-plugin"'
        GNOCCHI_ARCHIVE_POLICY_TEMPEST: "ceilometer-high-rate"
        CEILOMETER_BACKEND: "gnocchi"
        CEILOMETER_PIPELINE_INTERVAL: 15
      tempest_test_regex: telemetry_tempest_plugin
      tox_envlist: all

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches: ^(?!stable/(ocata|pike|queens|rocky)).*$

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches:
      - stable/pike
      - stable/queens
      - stable/rocky
    vars:
      devstack_localrc:
        GNOCCHI_ARCHIVE_POLICY_TEMPEST: "ceilometer-high"
        GNOCCHI_ARCHIVE_POLICY: "high"
        CEILOMETER_ALARM_AGGREGATION_METHOD: "mean"
        CEILOMETER_ALARM_METRIC_NAME: "cpu_util"

- job:
    name: telemetry-dsvm-integration-ipv6-only
    parent: devstack-tempest-ipv6
    branches: ^(?!stable/(ocata|pike|queens|rocky)).*$
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    required-projects: *base_required_projects
    vars: *base_vars

- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-ipv6-only
    gate:
      queue: telemetry
      jobs:
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-ipv6-only
