- job:
    name: telemetry-tempest-base
    parent: devstack-tempest
    description: |
      This job is for testing telemetry components.
    irrelevant-files:
      - ^\.gitreview$
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
    timeout: 7800
    required-projects: &base_required_projects
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-prometheus
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      - openstack/diskimage-builder
      - openstack/tempest
      - gnocchixyz/gnocchi
      - openstack-k8s-operators/sg-core
    vars: &base_vars
      configure_swap_size: 8192
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        ceilometer: https://opendev.org/openstack/ceilometer
        aodh: https://opendev.org/openstack/aodh
        sg-core: https://github.com/openstack-k8s-operators/sg-core
        devstack-plugin-prometheus: https://opendev.org/openstack/devstack-plugin-prometheus
      # NOTE(jokke): The following will disable the gabbi based integration tests for now.
      # We will need to figure out how we refactor them to be stable in the CI.
      tempest_exclude_regex: (^telemetry_tempest_plugin\.scenario\.test_telemetry_integration\.)
      devstack_services:
        tempest: true
        node_exporter: false
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/telemetry-tempest-plugin /opt/stack/heat-tempest-plugin"'
        GNOCCHI_ARCHIVE_POLICY_TEMPEST: "ceilometer-high-rate"
        CEILOMETER_BACKENDS: "gnocchi,sg-core"
        CEILOMETER_PIPELINE_INTERVAL: 15
        CEILOMETER_ALARM_THRESHOLD: 6000000000
        AODH_DEPLOY: uwsgi
        PROMETHEUS_CUSTOM_SCRAPE_TARGETS: "localhost:3000"
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              sg_core: True
            telemetry_services:
              metric_backends: gnocchi,prometheus
            telemetry:
              disable_ssl_certificate_validation: True
              ceilometer_polling_interval: 15
      tempest_test_regex: telemetry_tempest_plugin
      tox_envlist: all
      zuul_copy_output:
        /etc/prometheus/prometheus.yml: logs
        /etc/openstack/prometheus.yaml: logs

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base

- job:
    name: telemetry-dsvm-integration-2025-1
    parent: telemetry-tempest-base
    override-checkout: stable/2025.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6

- job:
    name: telemetry-dsvm-integration-2024-2
    parent: telemetry-tempest-base
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.2
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: &prefix_grouping_vars
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            telemetry:
              autoscaling_instance_grouping: prefix

- job:
    name: telemetry-dsvm-integration-2024-1
    parent: telemetry-tempest-base
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *prefix_grouping_vars

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches:
      - stable/2024.2
      - stable/2024.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *prefix_grouping_vars

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches:
      # TODO: We should switch to more recent version
      - unmaintained/2023.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.5
    vars: &no_prometheus_vars
      devstack_localrc:
        GLOBAL_VENV: False
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              sg_core: False
            telemetry_services:
              metric_backends: gnocchi
            telemetry:
              autoscaling_instance_grouping: prefix

- job:
    name: telemetry-dsvm-integration-ipv6-only-base
    parent: devstack-tempest-ipv6
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
    required-projects: *base_required_projects
    vars: *base_vars

- job:
    name: telemetry-dsvm-integration-ipv6-only
    parent: telemetry-dsvm-integration-ipv6-only-base
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    branches:
      - stable/2024.2
      - stable/2024.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *prefix_grouping_vars

- job:
    name: telemetry-dsvm-integration-ipv6-only
    parent: telemetry-dsvm-integration-ipv6-only-base
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    branches:
      # TODO: We should switch to more recent version
      - unmaintained/2023.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.5
    vars: *no_prometheus_vars

- job:
    name: telemetry-dsvm-integration-centos-9s
    nodeset: devstack-single-node-centos-9-stream
    parent: telemetry-dsvm-integration
    description: |
      Telemetry devstack tempest tests job for a Centos 9 stream system
    pre-run:
      - playbooks/python-3.12-install.yaml

- job:
    name: telemetry-dsvm-integration-centos-9s-fips
    parent: telemetry-dsvm-integration-centos-9s
    description: |
      Telemetry devstack tempest tests job for a FIPS enabled Centos 9 stream system
    pre-run:
      - playbooks/python-3.12-install.yaml
      - playbooks/enable-fips.yaml
    vars:
      nslookup_target: "opendev.org"

- job:
    name: telemetry-dsvm-integration-aetos
    parent: telemetry-tempest-base
    # NOTE(jwysogla): Let's keep the job non-voting for now. Before switching
    # to voting, we should:
    # - run this job in Aetos
    # - have Aodh do tenancy modification of queries
    # - have a few runs of the job to ensure stability
    voting: false
    description: This is a job to test telemetry with Aetos
    required-projects: &aetos_required_projects
      - openstack/aodh
      - openstack/ceilometer
      - openstack/devstack-plugin-prometheus
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      - openstack/diskimage-builder
      - openstack/tempest
      - openstack/python-observabilityclient
      - openstack/aetos
      - openstack-k8s-operators/sg-core
    vars: &aetos_vars
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        ceilometer: https://opendev.org/openstack/ceilometer
        aodh: https://opendev.org/openstack/aodh
        sg-core: https://github.com/openstack-k8s-operators/sg-core
        devstack-plugin-prometheus: https://opendev.org/openstack/devstack-plugin-prometheus
        aetos: https://opendev.org/openstack/aetos
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/telemetry-tempest-plugin /opt/stack/heat-tempest-plugin"'
        CEILOMETER_BACKENDS: "sg-core"
        CEILOMETER_PIPELINE_INTERVAL: 15
        CEILOMETER_ALARM_THRESHOLD: 6000000000
        AODH_DEPLOY: uwsgi
        PROMETHEUS_CUSTOM_SCRAPE_TARGETS: "localhost:3000"
        SG_CORE_CONFIGURE_OBSERVABILITYCLIENT: false
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              gnocchi: False

- job:
    name: telemetry-dsvm-integration-aetos-ipv6-only
    parent: telemetry-dsvm-integration-ipv6-only-base
    voting: false
    description: |
      Telemetry devstack tempest tests job with Aetos for IPv6-only deployment
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
    required-projects: *aetos_required_projects
    vars: *aetos_vars

- project:
    queue: telemetry
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-2024-1
        - telemetry-dsvm-integration-2024-2
        - telemetry-dsvm-integration-2025-1
        - telemetry-dsvm-integration-ipv6-only
        - telemetry-dsvm-integration-centos-9s
        - telemetry-dsvm-integration-centos-9s-fips
        - telemetry-dsvm-integration-aetos
        - telemetry-dsvm-integration-aetos-ipv6-only
    gate:
      jobs:
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-ipv6-only
