- job:
    name: telemetry-tempest-base
    parent: devstack-tempest
    description: |
      This job is for testing telemetry components. We test stable branches from wallaby onwards.
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
    timeout: 7800
    required-projects: &base_required_projects
      - openstack/aodh
      - openstack/ceilometer
      - openstack/telemetry-tempest-plugin
      - openstack/heat-tempest-plugin
      - openstack/heat
      - openstack/diskimage-builder
      - openstack/tempest
      - gnocchixyz/gnocchi
      - infrawatch/sg-core
    vars: &base_vars
      configure_swap_size: 8192
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        ceilometer: https://opendev.org/openstack/ceilometer
        aodh: https://opendev.org/openstack/aodh
        sg-core: https://github.com/infrawatch/sg-core
      # NOTE(jokke): The following will disable the gabbi based integration tests for now.
      # We will need to figure out how we refactor them to be stable in the CI.
      tempest_exclude_regex: (^telemetry_tempest_plugin\.scenario\.test_telemetry_integration\.)
      devstack_services:
        tempest: true
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/telemetry-tempest-plugin /opt/stack/heat-tempest-plugin"'
        GNOCCHI_ARCHIVE_POLICY_TEMPEST: "ceilometer-high-rate"
        CEILOMETER_BACKENDS: "gnocchi,sg-core"
        CEILOMETER_PIPELINE_INTERVAL: 15
        CEILOMETER_ALARM_THRESHOLD: 6000000000
        AODH_DEPLOY: uwsgi
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              sg_core: True
            telemetry_services:
              metric_backends: gnocchi,prometheus
            telemetry:
              disable_ssl_certificate_validation: True
              ceilometer_polling_interval: 15
      tempest_test_regex: telemetry_tempest_plugin
      tox_envlist: all

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base

- job:
    name: telemetry-dsvm-integration-2024-2
    parent: telemetry-tempest-base
    override-checkout: stable/2024.2
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: &prefix_grouping_vars
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              sg_core: True
            telemetry_services:
              metric_backends: gnocchi,prometheus
            telemetry:
              disable_ssl_certificate_validation: True
              ceilometer_polling_interval: 15
              autoscaling_instance_grouping: prefix

- job:
    name: telemetry-dsvm-integration-2024-1
    parent: telemetry-tempest-base
    override-checkout: stable/2024.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *prefix_grouping_vars

- job:
    name: telemetry-dsvm-integration-2023-2
    parent: telemetry-tempest-base
    override-checkout: stable/2023.2
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: &no_prometheus_vars
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/telemetry-tempest-plugin /opt/stack/heat-tempest-plugin"'
        GNOCCHI_ARCHIVE_POLICY_TEMPEST: "ceilometer-high-rate"
        CEILOMETER_BACKENDS: "gnocchi"
        CEILOMETER_PIPELINE_INTERVAL: 15
        CEILOMETER_ALARM_THRESHOLD: 6000000000
        GLOBAL_VENV: False
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              sg_core: False
            telemetry_services:
              metric_backends: gnocchi
            telemetry:
              disable_ssl_certificate_validation: True
              ceilometer_polling_interval: 15
              autoscaling_instance_grouping: prefix

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches:
      - stable/2024.2
      - stable/2024.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *prefix_grouping_vars

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches:
      - stable/2023.2
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *no_prometheus_vars

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches:
      - stable/2023.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.5
    vars: *no_prometheus_vars

- job:
    name: telemetry-dsvm-integration
    parent: telemetry-tempest-base
    branches:
      - stable/wallaby
    vars:
      devstack_localrc:
        USE_PYTHON3: False

- job:
    name: telemetry-dsvm-integration-ipv6-only-base
    parent: devstack-tempest-ipv6
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
    required-projects: *base_required_projects
    vars: *base_vars

- job:
    name: telemetry-dsvm-integration-ipv6-only
    parent: telemetry-dsvm-integration-ipv6-only-base
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    branches:
      - stable/2024.2
      - stable/2024.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *prefix_grouping_vars

- job:
    name: telemetry-dsvm-integration-ipv6-only
    parent: telemetry-dsvm-integration-ipv6-only-base
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    branches:
      - stable/2023.2
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.6
    vars: *no_prometheus_vars

- job:
    name: telemetry-dsvm-integration-ipv6-only
    parent: telemetry-dsvm-integration-ipv6-only-base
    description: |
      Telemetry devstack tempest tests job for IPv6-only deployment
    branches:
      - stable/2023.1
    required-projects:
      - name: gnocchixyz/gnocchi
        override-checkout: stable/4.5
    vars: *no_prometheus_vars

- job:
    name: telemetry-dsvm-integration-wallaby
    parent: telemetry-dsvm-integration
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby
    voting: false

- job:
    name: telemetry-dsvm-integration-centos-8s
    nodeset: devstack-single-node-centos-8-stream
    parent: telemetry-dsvm-integration
    branches:
      - stable/wallaby
      - stable/xena
      - stable/yoga
    description: |
      Telemetry devstack tempest test job for Centos 8 stream system using python 36
      i.e. yoga and below
    vars:
      devstack_localrc:
        # for versions of devstack that don't explicitly support rhel8
        FORCE: 'yes'
        TEMPEST_BRANCH: '30.1.0'
        TEMPEST_VENV_UPPER_CONSTRAINTS: '/opt/stack/requirements/upper-constraints.txt'

- job:
    name: telemetry-dsvm-integration-centos-8s-fips
    parent: telemetry-dsvm-integration-centos-8s
    description: |
      Telemetry devstack tempest tests job for a FIPS enabled Centos 8 stream system using python36
      i.e. yoga and below
    pre-run: playbooks/enable-fips.yaml
    vars:
      nslookup_target: 'opendev.org'

- job:
    name: telemetry-dsvm-integration-centos-9s
    nodeset: devstack-single-node-centos-9-stream
    parent: telemetry-dsvm-integration
    description: |
      Telemetry devstack tempest tests job for a Centos 9 stream system

- job:
    name: telemetry-dsvm-integration-centos-9s-fips
    parent: telemetry-dsvm-integration-centos-9s
    description: |
      Telemetry devstack tempest tests job for a FIPS enabled Centos 9 stream system
    pre-run: playbooks/enable-fips.yaml
    vars:
      nslookup_target: "opendev.org"

- project:
    queue: telemetry
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-2023-2
        - telemetry-dsvm-integration-2024-1
        - telemetry-dsvm-integration-2024-2
        - telemetry-dsvm-integration-ipv6-only
        - telemetry-dsvm-integration-centos-9s
        - telemetry-dsvm-integration-centos-9s-fips
    gate:
      jobs:
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-ipv6-only
