---
- hosts: all
  tasks:
    - name: Install Python 3.12 on Centos distro
      become: yes
      ansible.builtin.shell: |
        dnf install -y python3.12 python3.12-pip python3.12-devel pcp*devel gcc gcc-c++
        alternatives --install /usr/bin/python python /usr/bin/python3.12 10
        alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 10
        update-alternatives --set python /usr/bin/python3.12
        update-alternatives --set python3 /usr/bin/python3.12
        alternatives --install /usr/bin/pip pip /usr/bin/pip3.12 10
        alternatives --install /usr/bin/pip33 pip3 /usr/bin/pip3.12 10
        update-alternatives --set pip /usr/bin/pip3.12
        update-alternatives --set pip3 /usr/bin/pip3.12
        pip3.12 install pcp